# Path to your oh-my-zsh installation.
export ZSH="${ZSH:-$HOME/.oh-my-zsh}"

ZSH_THEME="gnzh"

plugins=(git)

if [[ -f "$ZSH/oh-my-zsh.sh" ]]; then
    source "$ZSH/oh-my-zsh.sh"
fi

# Developer env generated by setup-dev.sh from .dev/.env
[[ -f ~/.zsh-env ]] && source ~/.zsh-env

# Fragmentos compartidos. .zsh-local es opcional (overrides por máquina; gitignored en .dev/)
[[ -f ~/.zsh-basics ]] && source ~/.zsh-basics
[[ -f ~/.zsh-git ]] && source ~/.zsh-git
[[ -f ~/.zsh-node ]] && source ~/.zsh-go
[[ -f ~/.zsh-ssh ]] && source ~/.zsh-ssh
[[ -f ~/.zsh-local ]] && source ~/.zsh-local
